# Generated by Django 5.0.4 on 2024-05-04 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_staus_post_stauts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='stauts',
            new_name='status',
        ),
    ]
